project_id = "lkgomkokczyvftjrbejq"

[functions.generate-sculpture-pdf]
verify_jwt = false

[functions.import-sculptures]
verify_jwt = false

[functions.bulk-delete-sculptures]
verify_jwt = false

[functions.import-images-zip]
verify_jwt = false
