project_id = "lkgomkokczyvftjrbejq"

[api]
enabled = true
port = 54321
hostname = "127.0.0.1"

[db]
port = 54322
shadow_port = 54320

[studio]
enabled = true
port = 54323
hostname = "127.0.0.1"

[[functions]]
name = "generate-image"
verify_jwt = true